#!/usr/bin/env node

var path = require('path'),
    program = require('..');

program.version('0.0.1');

program.command('api', 'api desc', {
      bin: function (args) {
        return path.join('./', args[0], args[1] + '.js');
      },
      help: function () {
        console.log("api help");
      },
      executables: false,
      skipCount: 1
});

program.command('other')
  .description('other')
  .option('-v,--other-version [VERSION]', 'other version', 'v2')
  .action(function (options) {
    console.log(options);
  });

program.parse(process.argv);

// Try the following:
//   ./examples/api-custom api v1
//   ./examples/api-custom api v1 install -h
//   ./examples/api-custom api v1 install foo bar baz
//   ./examples/api-custom api v1 install foo bar baz --force
