#!/usr/bin/env node

var path = require('path'),
    program = require('..');

program
  .version('0.0.1')
  .command('api v1 [name]', 'api', {
//    dir: path.join(__dirname, './api'), bin: 'v1.js', beginIndex: 2

//    dir: './api', bin: 'v1.js', beginIndex: 2

//    dir: './api',
//    bin: function (args) {
//      return args[1] + '.js';
//    },
//    beginIndex: 2

      bin: function (args) {
        return path.join('./', args[0], args[1] + '.js');
      },
      beginIndex: 2
  })
  .parse(process.argv);

// Try the following:
//   ./examples/api-custom api v1
//   ./examples/api-custom api v1 install -h
//   ./examples/api-custom api v1 install foo bar baz
//   ./examples/api-custom api v1 install foo bar baz --force
